# Use an official Miniconda3 image as the base image
FROM node:22-alpine3.20 AS build

# # Install Node.js (required for the frontend)
# RUN apt-get update 
# RUN apt-get install -y curl
# RUN apt-get install -y nodejs
 
# Set the working directory for the frontend
WORKDIR /app

COPY package.json package-lock.json ./
ENV NODE_OPTIONS="--max-old-space-size=8192"
RUN npm ci --verbose

COPY . .
# RUN npm run build 
EXPOSE 5173   

# Command to run both the backend and frontend
# CMD (npm run dev)