# receivers:
#   otlp:
#     protocols:
#       grpc:
#       http:

# exporters:
#   prometheus:
#     endpoint: "otel-collector:8889"

# service:
#   pipelines:
#     metrics:
#       receivers: [otlp]
#       exporters: [prometheus]

receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    # traces:
    #   receivers: [otlp]
    #   exporters: []
