receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: jaeger:4317  # OTLP gRPC exporter to Jaeger
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:9090"

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, debug]

    metrics:
      receivers: [otlp]
      exporters: [prometheus, debug]

  telemetry:
    metrics:
      address: "0.0.0.0:9090"
