receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:

exporters:
  logging: 
  prometheus:
    endpoint: "0.0.0.0:9090"

  jaeger:
    endpoint: "jaeger:14250"  # gRPC endpoint used by Jaeger collector
    tls:
      insecure: true

      
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger, logging]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [ prometheus]
