"""add features and pages

Revision ID: 89bb05af2188
Revises: 4af623372c9d
Create Date: 2025-11-11 04:37:03.650266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = '89bb05af2188'
down_revision: Union[str, None] = '4af623372c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_contents',
        sa.Column('id', sa.UUID(), primary_key=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('intro', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.Column('seo_title', sa.String(), nullable=False),
        sa.Column('seo_description', sa.Text(), nullable=False),
        sa.Column('meta_keywords', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('canonical_url', sa.String(), nullable=False),
        sa.Column('meta_robots', sa.String(), server_default='index,follow', nullable=False),
        sa.Column('locale', sa.String(), server_default='en', nullable=False),
        sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
        sa.Column('svg_icon', sa.Text(), nullable=True),
        sa.Column('icon_url', sa.String(), nullable=True),
        sa.Column('icon_reference', sa.JSON(), nullable=True),
        sa.Column('open_graph', sa.JSON(), nullable=True),
        sa.Column('twitter_card', sa.JSON(), nullable=True),
        sa.Column('structured_data', sa.JSON(), nullable=True),
        sa.Column('meta_tags', sa.JSON(), nullable=True),
        sa.Column('schema_org_jsonld', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_page_contents_'))
    )
    
    # Create indexes
    # op.create_index(op.f('ix_page_contents_id'), 'page_contents', ['id'], unique=True)
    op.create_index(op.f('ix_page_contents_slug'), 'page_contents', ['slug'], unique=True)
    op.create_index(op.f('ix_page_contents_title'), 'page_contents', ['title'], unique=False)
    op.create_index(op.f('ix_page_contents_order_index'), 'page_contents', ['order_index'], unique=False)
    op.create_index(op.f('ix_page_contents_locale'), 'page_contents', ['locale'], unique=False)
    op.create_index(op.f('ix_page_contents_created_at'), 'page_contents', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_contents_updated_at'), 'page_contents', ['updated_at'], unique=False)
    op.create_index(op.f('ix_page_contents_is_published'), 'page_contents', ['is_published'], unique=False)
    
    # Composite indexes for common query patterns
    # ### end Alembic commands ###


    op.create_table('page_features',
        sa.Column('id', sa.UUID(), primary_key=True, nullable=False),
        sa.Column('page_id', sa.UUID(), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False, server_default='0'),
        
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('subtitle', sa.String(length=512), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('image_path', sa.String(length=1024), nullable=True),
        sa.Column('icon_name', sa.String(length=128), nullable=True),
        
        
        sa.Column('seo_title', sa.String(), nullable=False),
        sa.Column('seo_description', sa.Text(), nullable=False),
        sa.Column('meta_keywords', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('canonical_url', sa.String(), nullable=False),
        sa.Column('meta_robots', sa.String(), server_default='index,follow', nullable=False),
        sa.Column('locale', sa.String(), server_default='en', nullable=False),
        sa.Column('svg_icon', sa.Text(), nullable=True),
        sa.Column('icon_url', sa.String(), nullable=True),
        sa.Column('icon_reference', sa.JSON(), nullable=True),
        sa.Column('open_graph', sa.JSON(), nullable=True),
        sa.Column('twitter_card', sa.JSON(), nullable=True),
        sa.Column('structured_data', sa.JSON(), nullable=True),
        sa.Column('meta_tags', sa.JSON(), nullable=True),
        sa.Column('schema_org_jsonld', sa.JSON(), nullable=True),
        
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.ForeignKeyConstraint(['page_id'], ['page_contents.id'], name='fk_feature_page_contents_id', ondelete='CASCADE')
    )
    # op.create_index('ix_feature_page_id', 'page_features', ['id'], unique=True) 
    op.create_index('ix_feature_page_order_index', 'page_features', ['order_index'], unique=False)
    op.create_index('ix_feature_page_locale', 'page_features', ['locale'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_page_id', table_name='page_features')
    op.drop_index('ix_feature_page_order_index', table_name='page_features')
    op.drop_table('page_features') 
    
    op.drop_index('ix_page_contents_id', table_name='page_contents')
    op.drop_index('ix_page_contents_slug', table_name='page_contents')
    op.drop_index('ix_page_contents_updated_at', table_name='page_contents')
    op.drop_index('ix_page_contents_created_at', table_name='page_contents')
    op.drop_index('ix_page_contents_locale', table_name='page_contents')
    op.drop_index('ix_page_contents_order_index', table_name='page_contents')
    op.drop_index('ix_page_contents_title', table_name='page_contents')
    op.drop_index('ix_page_contents_is_published', table_name='page_contents')
    op.drop_table('page_contents')
    # ### end Alembic commands ###
