"""add payments table

Revision ID: a490017e16fa
Revises: a5c220713937
Create Date: 2025-11-01 10:41:32.517802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a490017e16fa'
down_revision: Union[str, None] = 'a5c220713937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email_verification_token", sa.String(), nullable=True, default=None))
    op.add_column("user", sa.Column("status", sa.String(), nullable=True, default="pending"))
    op.add_column("user", sa.Column("is_email_verified", sa.Boolean(), nullable=True, default=False))
    op.add_column("user", sa.Column("is_email_verified_at", sa.BigInteger(), nullable=True, default=None))



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "email_verification_token")
    op.drop_column("user", "status")
    op.drop_column("user", "is_email_verified")
    op.drop_column("user", "is_email_verified_at")
